---
# Retrieve Vault Infra token

- name: Get Vault Infra keys and token
  block:
    - name: Get Vault Infra keys
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.vaultInfra.namespace }}"
        kind: Secret
        name: "{{ dsc_name }}-vault-keys"
      register: vault_infra_keys

    - name: Get Vault Infra token
      ansible.builtin.set_fact:
        vault_infra_token: "{{ vault_infra_keys.resources[0].data.root_token | b64decode }}"

# Write Vault Infra secrets

- name: Write secrets
  ansible.builtin.include_tasks: write.yml
  loop: "{{ envs | subelements('apps') }}"
  loop_control:
    label: "{{ item.0.name }}"
