---
- name: Find gitlab token in inventory
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.console.namespace }}"
    kind: Secret
    name: dso-config
  register: ansible_inventory

- name: Get gitlab token
  ansible.builtin.set_fact:
    gitlab_token: "{{ ansible_inventory.resources[0].data.GITLAB_TOKEN | b64decode }}"
  when: ansible_inventory.resources[0].data.GITLAB_TOKEN is defined and ansible_inventory.resources[0].data.GITLAB_TOKEN | length != 0
  register: set_token_inv

- name: Create Catalog
  community.general.gitlab_project:
    api_url: https://{{ gitlab_domain }}
    api_token: "{{ gitlab_token }}"
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    import_url: "{{ dsc.gitlabCatalog.catalogRepoUrl }}"
    name: Catalog
    path: catalog
    group: "{{ dsc.global.projectsRootDir | join('/') }}"
    visibility: internal
  register: catalog_repo

- name: Synchronize repo
  ansible.builtin.include_tasks:
    file: sync.yaml
  when: not dsc.global.offline
