---
- name: Create Argo CD namespace
  kubernetes.core.k8s:
    name: "{{ dsc.argocd.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

# OpenShift CRB

- name: Argo CD OpenShift scc crb
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        creationTimestamp:
        name: "{{ dsc_name }}-argo-socle-argocd-system:openshift:scc:privileged"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:privileged
      subjects:
        - kind: ServiceAccount
          namespace: "{{ dsc.argocd.namespace }}"
          name: "{{ dsc_name }}-argo-socle-argocd-repo-server"
        - kind: ServiceAccount
          namespace: "{{ dsc.argocd.namespace }}"
          name: argocd-server
        - kind: ServiceAccount
          namespace: "{{ dsc.argocd.namespace }}"
          name: "{{ dsc_name }}-argo-socle-redis"
        - kind: ServiceAccount
          namespace: "{{ dsc.argocd.namespace }}"
          name: "{{ dsc_name }}-argo-socle-redis-ha"
        - kind: ServiceAccount
          namespace: "{{ dsc.argocd.namespace }}"
          name: "{{ dsc_name }}-argo-socle-redis-ha-haproxy"

# Vault plugin setup

- name: Get Argo CD app version
  block:
    - name: Add Argo CD helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "{{ dsc.argocd.helmRepoUrl }}"
        force_update: true

    - name: Retrieve Argo CD Helm infos
      changed_when: false
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          helm search repo -l argo --version "{{ dsc.argocd.chartVersion }}" | tail -n 1
        executable: /bin/bash
      register: argo_infos

    - name: Set argo_app_version fact
      ansible.builtin.set_fact:
        argo_app_version: "{{ argo_infos.stdout | regex_search('v([0-9]*\\.)+([0-9]+)') }}"

- name: Retrieve Vault infra token
  block:
    - name: Get Vault infra secrets
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.vaultInfra.namespace }}"
        kind: Secret
      register: vault_infra_secrets

    - name: Get Vault infra keys secret name
      ansible.builtin.set_fact:
        vault_infra_keys_secret: "{{ vault_infra_secrets.resources
          | map(attribute='metadata.name')
          | select('contains', 'vault-keys') | first }}"

    - name: Find Vault infra keys
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.vaultInfra.namespace }}"
        kind: Secret
        name: "{{ vault_infra_keys_secret }}"
      register: vault_infra_keys

    - name: Set fact for Vault infra secrets
      ansible.builtin.set_fact:
        vault_infra_token: "{{ vault_infra_keys.resources[0].data.root_token | b64decode }}"

- name: Deploy Argo CD Vault plugin config
  kubernetes.core.k8s:
    template: "{{ item }}"
    state: present
  with_items:
    - vault-plugin-cm.yml.j2
    - vault-plugin-secret.yml.j2

# Argo CD installation

- name: Set path fact
  ansible.builtin.set_fact:
    path: "{{ role_path + '/templates/values' }}"

- name: Compute ArgoCD Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc.argocd['values'] }}"
    combine_dest_var: "argo_values"

- name: Create Argo CD application
  kubernetes.core.k8s:
    name: "{{ dsc_name }}-argo-socle"
    namespace: "{{ dsc.argocdInfra.namespace }}"
    api_version: argoproj.io/v1alpha1
    kind: Application
    state: present
    template: argocd-app-spec.yaml.j2

- name: Wait Argo CD namespace
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ dsc.argocd.namespace }}"
  register: argocd_ns
  until: argocd_ns.resources | length > 0
  retries: 25
  delay: 5

- name: Install routes
  kubernetes.core.k8s:
    template: "{{ item }}"
  with_items:
    - ingress.yaml.j2

- name: Wait Argo CD URL
  ansible.builtin.uri:
    url: https://{{ argocd_domain }}
    method: GET
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    status_code: [200, 202]
    return_content: false
  register: argocd_response
  until: argocd_response is not failed
  retries: 25
  delay: 5

# Alerting and monitoring setup

- name: Set alerting rules
  when: dsc.global.alerting.enabled
  kubernetes.core.k8s:
    template: prometheusrule.yml.j2

- name: Patch serviceMonitors
  when: >
    dsc.global.metrics.enabled and
    dsc.global.metrics.additionalLabels is defined
  block:
    - name: Get serviceMonitors
      kubernetes.core.k8s_info:
        api_version: monitoring.coreos.com/v1
        kind: ServiceMonitor
        namespace: "{{ dsc.argocd.namespace }}"
      register: service_monitors

    - name: Get service_monitors names
      ansible.builtin.set_fact:
        service_monitors_names: "{{ service_monitors.resources | map(attribute='metadata.name') }}"

    - name: Patch serviceMonitors
      kubernetes.core.k8s:
        kind: ServiceMonitor
        namespace: "{{ dsc.argocd.namespace }}"
        state: patched
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              "{{ dsc.global.metrics.additionalLabels }}"
      loop: "{{ service_monitors_names }}"
