---
- name: Template values.j2 and write to destination
  ansible.builtin.template:
    src: "{{ item }}-values.j2"
    dest: "gitops/apps/{{ item }}/values/dso-hp-testcm.yaml"
    mode: '0644'
  loop:
    - vault
