---
- name: Set path fact
  ansible.builtin.set_fact:
    path: "{{ role_path + '/templates/' + item + '/values' }}"

- name: Compute "{{ item }}" Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc[item]['values'] }}"
    combine_dest_var: "{{ item }}_values"

- name: Template values.j2 and write to destination
  ansible.builtin.copy:
    content: "{{ lookup('vars', item ~ '_values') | to_nice_yaml(indent=2) }}"
    dest: "gitops/apps/{{ item }}/values/dso-hp-testcm.yaml"
    mode: '0644'
