apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dso-install-app
  namespace: infra-argo
spec:
  project: default
  revisionHistoryLimit: 3
  sources:
  - repoURL: https://github.com/cloud-pi-native/socle.git
    targetRevision: refactor/gitops
    path: ./gitops
    directory:
      include: dso-appset.yaml
  destination:
    name: in-cluster
    namespace: infra-argo
  syncPolicy:
    # automated: {}
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
