---
envs:
  - name: dso-hp-testcm
    apps:
      - argocd_app: "keycloak"
        vault_values:
          global:
            imageRegistry: "{{ harbor_domain }}/dockerhub"
          auth:
            adminUser: "admin"
            adminPassword: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
          ingress:
            ingressClassName: "openshift-default"
            hostname: "{{ keycloak_domain }}"
            annotations:
              cluster-issuer: "acme-issuer"
      - argocd_app: "kubeview"
        vault_values:
          replicaCount: 3
