---
envs:
  - name: dso-hp-testcm
    apps:
      - argocd_app: "keycloak"
        vault_values:
          global:
            imageRegistry: "{{ dsc.global.registry }}"
          image:
            registry: "{{ dsc.global.registry }}"
          auth:
            adminPassword: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
          initcontainers:
            curlVersion: 8.8.0
            pluginDownloadUrl: "{{ dsc.keycloak.pluginDownloadUrl }}"
          ingress:
            ingressClassName: "openshift-default"
            hostname: "{{ keycloak_domain }}"
            annotations:
              cluster-issuer: "acme-issuer"
      - argocd_app: "kubeview"
        vault_values:
          replicaCount: 3
